{
 "title": "CDH Local Host Dashboard (Isilon)",
 "description": "This is a simple dashboard i use to monitor cloudera hosts.  ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "load_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "select load_1" }
   ]
  },
  {
   "title": "load_5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "select load_5" }
   ]
  },
  {
   "title": "load_15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "select load_15" }
   ]
  },
  {
   "title": "Disk Await Time Across Disks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "SELECT await_time_across_disks WHERE category=host"
    }
   ]
  },
  {
   "title": "Disk Service Time Across Disks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "SELECT service_time_across_disks  WHERE category=host"
    }
   ]
  },
  {
   "title": "Loal Disk Reads",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "select total_read_bytes_rate_across_disks where category = host"
    }
   ]
  },
  {
   "title": "Local Disk Writes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "select total_write_bytes_rate_across_disks where category = host"
    }
   ]
  },
  {
   "title": "Total Network Bytes transmitted across network interfaces",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "SELECT total_bytes_transmit_rate_across_network_interfaces where category=HOST"
    }
   ]
  },
  {
   "title": "Total Network Bytes received across network interfaces",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "SELECT total_bytes_receive_rate_across_network_interfaces where category=HOST"
    }
   ]
  }
 ]
}