# common_lib/conn_kit_constants.py

class ConnKitConstant:
    SFTP_CONN_DEFAULT = "SFTP_DEFAULT"
    SFTP_CONN_ACQ_POS = "SFTP_ACQ_POS"
    EMAIL_ACCT_DEFAULT = "EMAIL_DEFAULT"
    EMAIL_TEMPLATE_DEFAULT = "EMAIL_TEMPLATE"
    EMAIL_ATTACH_PATH = "EMAIL_ATTACH_DEFAULT"
    ARCHIVE_ATTACH = "ARCHIVE_ATTACH"