# common_lib/export/constants.py

class DataConstant:
    DEFAULT = "DEFAULT"

    IMPORT_CONFIG_KEY_DEFAULT = "FILE_IMPORT_DEFAULT"
    EXPORT_CONFIG_KEY_DEFAULT = "FILE_EXPORT_DEFAULT"
    ARCHIVE_IMPORT = "ARCHIVE_IMPORT"
    ARCHIVE_SFTP = "ARCHIVE_SFTP"

    RPT_EXCEL_FILE_TYPE = "xlsx"
    RPT_EXCEL_FILE_TYPE_OLD = "xls"
    RPT_TEXT_FILE_TYPE = "txt"
    RPT_CSV_FILE_TYPE = "csv"
    RPT_JSON_FILE_TYPE = "json"

    # import template keys (giữ lại nếu sau này dùng)
    IMP_TMP_ACQ_POS_MDR_FEE = "ACQ_POS_MDR_FEE"
    IMP_TMP_ACQ_BANK_FEE = "ACQ_BANK_FEE"
    IMP_MERCHANT_INFO = "IMP_MERCHANT_INFO"
    IMP_ACQ_VPB_ONL_TXN = "IMP_ACQ_VPB_ONL_TXN"
    IMP_ATOM_SET_TXN = "ATOM_POS_SET_TXN"
    ACQ_BANK_BENEFIT = "ACQ_BANK_BENEFIT"

    # External process
    EXTERNAL_MODULE_NAME = "externalTaskModule"